using System;
using System.IO;
using System.Text;
using AkaiS950Engine;

/// <summary>
/// Write what the C# engine computes, as a C++ header.
///
/// The port in Plugin/ cannot be compiled on the machine this was written on - there is no
/// C++ compiler here - so it cannot be checked by running it. What can be done is to leave
/// it something exact to be checked against: this prints the numbers the working engine
/// produces for a spread of inputs, and Plugin/Tests/ConformanceCheck.cpp holds the port to
/// them. Both then answer to the same measurements of the same machine.
///
/// Run it again after any change to Cal, Filter or the envelopes, and the port has to
/// follow or say why.
/// </summary>
static class ReferenceDump
{
    static int Main(string[] args)
    {
        string path = args.Length > 0
            ? args[0]
            : Path.Combine("Plugin", "Tests", "Reference.h");

        var s = new StringBuilder();

        s.AppendLine("#pragma once");
        s.AppendLine();
        s.AppendLine("/*");
        s.AppendLine(" * What the C# engine computes, for the port to be held to.");
        s.AppendLine(" *");
        s.AppendLine(" * GENERATED by AkaiS950Tests/ReferenceDump.cs - do not edit by hand. Regenerate it");
        s.AppendLine(" * after any change to Cal, Filter or the envelopes, and make the port follow.");
        s.AppendLine(" *");
        s.AppendLine(" * Every number here traces back to a recording of a real S950. Two implementations");
        s.AppendLine(" * already agree to the digit on them - the C# and the web's audio.js - and this is");
        s.AppendLine(" * how the third joins them.");
        s.AppendLine(" */");
        s.AppendLine();
        s.AppendLine("namespace reference");
        s.AppendLine("{");

        // ---------------------------------------------------------------- the filter

        s.AppendLine("    // cutoffHz (stored, rate) -> hertz");
        s.AppendLine("    struct Cutoff { int stored; double rate, hz; };");
        s.AppendLine();
        s.AppendLine("    inline constexpr Cutoff cutoffs[] =");
        s.AppendLine("    {");

        double[] rates = { 44100, 48000, 10000, 12500, 40000 };
        int[] stored = { 0, 10, 20, 30, 40, 45, 50, 55, 60, 70, 80, 90, 99 };

        foreach (double rate in rates)
            foreach (int v in stored)
                s.AppendLine("        { " + v + ", " + F(rate) + ", " +
                             F(Cal.CutoffHz(v, rate)) + " },");

        s.AppendLine("    };");
        s.AppendLine();

        // ------------------------------------------------------------- the envelopes

        s.AppendLine("    // envSeconds (stored) -> seconds");
        s.AppendLine("    struct EnvTime { int stored; double seconds; };");
        s.AppendLine();
        s.AppendLine("    inline constexpr EnvTime envTimes[] =");
        s.AppendLine("    {");

        for (int v = 0; v <= 99; v += 3)
            s.AppendLine("        { " + v + ", " + F(Cal.EnvSeconds(v)) + " },");
        s.AppendLine("        { 99, " + F(Cal.EnvSeconds(99)) + " },");

        s.AppendLine("    };");
        s.AppendLine();

        /*
         * Every setting of the VCA attack, not every third.
         *
         * It is a counter, so the interesting thing about it is where it steps, and a ladder
         * that samples one value in three would step somewhere different in the port without
         * anything noticing. All hundred, and they are cheap.
         */
        s.AppendLine("    // vcaAttackSeconds (stored) -> seconds");
        s.AppendLine("    struct VcaAttack { int stored; double seconds; };");
        s.AppendLine();
        s.AppendLine("    inline constexpr VcaAttack vcaAttacks[] =");
        s.AppendLine("    {");

        for (int v = 0; v <= 99; v++)
            s.AppendLine("        { " + v + ", " + F(Cal.VcaAttackSeconds(v)) + " },");

        s.AppendLine("    };");
        s.AppendLine();

        // -------------------------------------------------------------------- the LFO

        s.AppendLine("    // the LFO rate in hertz, from the stored byte");
        s.AppendLine("    struct LfoRate { int stored; double hz; };");
        s.AppendLine();
        s.AppendLine("    inline constexpr LfoRate lfoRates[] =");
        s.AppendLine("    {");

        for (int v = 0; v <= 99; v += 9)
            s.AppendLine("        { " + v + ", " +
                         F(Cal.LfoRateHzAtZero + v * Cal.LfoRateHzPerUnit) + " },");

        s.AppendLine("    };");
        s.AppendLine();

        s.AppendLine("    // the LFO delay fade, in seconds to full depth");
        s.AppendLine("    struct LfoFade { int stored; double seconds; };");
        s.AppendLine();
        s.AppendLine("    inline constexpr LfoFade lfoFades[] =");
        s.AppendLine("    {");

        int[] delays = { 0, 25, 50, 75, 85, 92, 96, 99 };
        foreach (int v in delays)
            s.AppendLine("        { " + v + ", " +
                         F(Cal.LfoDelayFadeConstant / Math.Max(1, 100 - v)) + " },");

        s.AppendLine("    };");
        s.AppendLine();

        // -------------------------------------------------------------- the constants

        s.AppendLine("    // the measured constants themselves, so a typo in a digit is caught");
        s.AppendLine("    inline constexpr double MaxRatio             = " + F(Cal.MaxRatio) + ";");
        s.AppendLine("    inline constexpr double FloorHz              = " + F(Cal.FloorHz) + ";");
        s.AppendLine("    inline constexpr double KeyFull              = " + F(Cal.KeyFull) + ";");
        s.AppendLine("    inline constexpr double VelOctaves           = " + F(Cal.VelOctaves) + ";");
        s.AppendLine("    inline constexpr double VelPivot             = " + F(Cal.VelPivot) + ";");
        s.AppendLine("    inline constexpr double EnvOctaves           = " + F(Cal.EnvOctaves) + ";");
        s.AppendLine("    inline constexpr double VcaAttackSpan        = " + F(Cal.VcaAttackSpan) + ";");
        s.AppendLine("    inline constexpr double VcfTimeScale         = " + F(Cal.VcfTimeScale) + ";");
        s.AppendLine("    inline constexpr double SustainDb            = " + F(Cal.SustainDb) + ";");
        s.AppendLine("    inline constexpr double LoudnessDbPerUnit    = " + F(Cal.LoudnessDbPerUnit) + ";");
        s.AppendLine("    inline constexpr double VelDbPerStep         = " + F(Cal.VelDbPerStep) + ";");
        s.AppendLine("    inline constexpr double LfoDepthCentsPerUnit = " + F(Cal.LfoDepthCentsPerUnit) + ";");
        s.AppendLine("    inline constexpr double LfoWheelCentsAtFull  = " + F(Cal.LfoWheelCentsAtFull) + ";");
        s.AppendLine("}");

        string dir = Path.GetDirectoryName(Path.GetFullPath(path));
        if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);
        File.WriteAllText(path, s.ToString());

        Console.WriteLine();
        Console.WriteLine("  wrote " + path);
        Console.WriteLine("  " + (rates.Length * stored.Length) + " cutoffs, " +
                          "34 envelope times, 12 LFO rates, " + delays.Length + " fades");
        Console.WriteLine();
        return 0;
    }

    /// <summary>Enough digits that a double survives the round trip.</summary>
    static string F(double v)
    {
        return v.ToString("R", System.Globalization.CultureInfo.InvariantCulture);
    }
}
