#pragma once

/*
 * What the C# engine computes, for the port to be held to.
 *
 * GENERATED by AkaiS950Tests/ReferenceDump.cs - do not edit by hand. Regenerate it
 * after any change to Cal, Filter or the envelopes, and make the port follow.
 *
 * Every number here traces back to a recording of a real S950. Two implementations
 * already agree to the digit on them - the C# and the web's audio.js - and this is
 * how the third joins them.
 */

namespace reference
{
    // cutoffHz (stored, rate) -> hertz
    struct Cutoff { int stored; double rate, hz; };

    inline constexpr Cutoff cutoffs[] =
    {
        { 0, 44100, 311 },
        { 10, 44100, 311 },
        { 20, 44100, 311 },
        { 30, 44100, 544 },
        { 40, 44100, 1138 },
        { 45, 44100, 1585.8688470362233 },
        { 50, 44100, 2210 },
        { 55, 44100, 3249.859996984485 },
        { 60, 44100, 4779 },
        { 70, 44100, 8783 },
        { 80, 44100, 16317 },
        { 90, 44100, 16317 },
        { 99, 44100, 16317 },
        { 0, 48000, 311 },
        { 10, 48000, 311 },
        { 20, 48000, 311 },
        { 30, 48000, 544 },
        { 40, 48000, 1138 },
        { 45, 48000, 1585.8688470362233 },
        { 50, 48000, 2210 },
        { 55, 48000, 3249.859996984485 },
        { 60, 48000, 4779 },
        { 70, 48000, 8783 },
        { 80, 48000, 17760 },
        { 90, 48000, 17760 },
        { 99, 48000, 17760 },
        { 0, 10000, 311 },
        { 10, 10000, 311 },
        { 20, 10000, 311 },
        { 30, 10000, 544 },
        { 40, 10000, 1138 },
        { 45, 10000, 1585.8688470362233 },
        { 50, 10000, 2210 },
        { 55, 10000, 3249.859996984485 },
        { 60, 10000, 3700 },
        { 70, 10000, 3700 },
        { 80, 10000, 3700 },
        { 90, 10000, 3700 },
        { 99, 10000, 3700 },
        { 0, 12500, 311 },
        { 10, 12500, 311 },
        { 20, 12500, 311 },
        { 30, 12500, 544 },
        { 40, 12500, 1138 },
        { 45, 12500, 1585.8688470362233 },
        { 50, 12500, 2210 },
        { 55, 12500, 3249.859996984485 },
        { 60, 12500, 4625 },
        { 70, 12500, 4625 },
        { 80, 12500, 4625 },
        { 90, 12500, 4625 },
        { 99, 12500, 4625 },
        { 0, 40000, 311 },
        { 10, 40000, 311 },
        { 20, 40000, 311 },
        { 30, 40000, 544 },
        { 40, 40000, 1138 },
        { 45, 40000, 1585.8688470362233 },
        { 50, 40000, 2210 },
        { 55, 40000, 3249.859996984485 },
        { 60, 40000, 4779 },
        { 70, 40000, 8783 },
        { 80, 40000, 14800 },
        { 90, 40000, 14800 },
        { 99, 40000, 14800 },
    };

    // envSeconds (stored) -> seconds
    struct EnvTime { int stored; double seconds; };

    inline constexpr EnvTime envTimes[] =
    {
        { 0, 0.0016799999999999999 },
        { 3, 0.0022208611294229287 },
        { 6, 0.0029358477120129088 },
        { 9, 0.0038810178961397081 },
        { 12, 0.0051304772548401373 },
        { 15, 0.0067821889944422106 },
        { 18, 0.0089656547084266 },
        { 21, 0.01185206788200732 },
        { 24, 0.015667736227638094 },
        { 27, 0.020711825222626708 },
        { 30, 0.027379814021626821 },
        { 33, 0.036194502792535638 },
        { 36, 0.047847002589721473 },
        { 39, 0.063250921554113451 },
        { 42, 0.083613995880779474 },
        { 45, 0.1105327817424714 },
        { 48, 0.1461178324397876 },
        { 51, 0.19315917522681958 },
        { 54, 0.25534506193609274 },
        { 57, 0.33755114443092804 },
        { 60, 0.44622274753504337 },
        { 63, 0.589880211348142 },
        { 66, 0.77978692404694649 },
        { 69, 1.0308324219334135 },
        { 72, 1.3626997957266744 },
        { 75, 1.8014089329773428 },
        { 78, 2.3813565937170318 },
        { 81, 3.1480132704054467 },
        { 84, 4.1614882780660745 },
        { 87, 5.5012425936345837 },
        { 90, 7.2723189522195355 },
        { 93, 9.61357766770837 },
        { 96, 12.708583902917768 },
        { 99, 16.8 },
        { 99, 16.8 },
    };

    // the LFO rate in hertz, from the stored byte
    struct LfoRate { int stored; double hz; };

    inline constexpr LfoRate lfoRates[] =
    {
        { 0, 1.785 },
        { 9, 2.58753 },
        { 18, 3.39006 },
        { 27, 4.19259 },
        { 36, 4.99512 },
        { 45, 5.79765 },
        { 54, 6.60018 },
        { 63, 7.40271 },
        { 72, 8.20524 },
        { 81, 9.0077699999999989 },
        { 90, 9.8103 },
        { 99, 10.61283 },
    };

    // the LFO delay fade, in seconds to full depth
    struct LfoFade { int stored; double seconds; };

    inline constexpr LfoFade lfoFades[] =
    {
        { 0, 0.0833 },
        { 25, 0.11106666666666666 },
        { 50, 0.1666 },
        { 75, 0.3332 },
        { 85, 0.55533333333333335 },
        { 92, 1.04125 },
        { 96, 2.0825 },
        { 99, 8.33 },
    };

    // the measured constants themselves, so a typo in a digit is caught
    inline constexpr double MaxRatio             = 0.37;
    inline constexpr double FloorHz              = 311;
    inline constexpr double KeyFull              = 50;
    inline constexpr double VelOctaves           = 8.34;
    inline constexpr double VelPivot             = 65;
    inline constexpr double EnvOctaves           = 8.3;
    inline constexpr double AttackScale          = 1.33;
    inline constexpr double VcfTimeScale         = 0.78;
    inline constexpr double SustainDb            = 39.6;
    inline constexpr double LoudnessDbPerUnit    = 0.29;
    inline constexpr double VelDbPerStep         = 0.63;
    inline constexpr double LfoDepthCentsPerUnit = 1.527;
    inline constexpr double LfoWheelCentsAtFull  = 72.3;
}
